import * as stylex from "@stylexjs/stylex";

import { tokens } from "@/lib/stylex/tokens.stylex";

export const MONO = "ui-monospace, SFMono-Regular, Menlo, monospace";

export const s = stylex.create({
  shell: {
    position: "relative",
    width: "100%",
    minHeight: "320px",
    overflow: "hidden",
    borderRadius: "10px",
    backgroundColor: tokens.colorSurfaceSunken,
  },
  map: { width: "100%", height: "100%" },
  placeholder: {
    height: "100%",
    minHeight: "320px",
    display: "grid",
    placeItems: "center",
    padding: "28px",
    textAlign: "center",
  },
  placeholderContent: {
    maxWidth: "330px",
    display: "grid",
    justifyItems: "center",
    gap: "8px",
  },
  placeholderIcon: { color: tokens.colorAccent },
  placeholderTitle: {
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 750,
  },
  placeholderCopy: {
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    lineHeight: 1.45,
  },
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: "7px",
    marginTop: "4px",
  },
  primaryButton: {
    minHeight: "32px",
    paddingInline: "12px",
    borderWidth: 0,
    borderRadius: "8px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    outlineOffset: "2px",
    backgroundColor: tokens.colorAccent,
    color: tokens.colorOnAccent,
    cursor: "pointer",
    fontSize: tokens.fontSizeXs,
    fontWeight: 750,
  },
  mapControls: {
    position: "absolute",
    top: "8px",
    left: "10px",
    zIndex: 3,
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  utilityButton: {
    minWidth: "30px",
    height: "30px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    paddingInline: "8px",
    borderWidth: 0,
    borderRadius: "8px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    outlineOffset: "2px",
    backgroundColor: {
      default: "light-dark(rgba(255,255,255,.95), rgba(20,24,32,.95))",
      ":disabled": tokens.colorSurfaceSunken,
    },
    boxShadow: tokens.shadowNode,
    color: {
      default: tokens.colorTextEmphasis,
      ":disabled": tokens.colorTextDisabled,
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    fontSize: "10px",
    fontWeight: 700,
    backdropFilter: "blur(12px)",
  },
  inspector: {
    position: "absolute",
    top: "46px",
    left: "10px",
    zIndex: 3,
    width: "min(292px, calc(100% - 20px))",
    maxHeight: "calc(100% - 58px)",
    display: "grid",
    gap: "6px",
    overflowY: "auto",
    padding: "8px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    borderRadius: "10px",
    backgroundColor: "light-dark(rgba(255,255,255,.97), rgba(20,24,32,.97))",
    boxShadow: tokens.shadowNodeRaised,
    backdropFilter: "blur(14px)",
  },
  inspectorHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    paddingInline: "2px",
  },
  inspectorTitle: {
    color: tokens.colorTextEmphasis,
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  layer: {
    display: "grid",
    gap: "6px",
    padding: "7px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
  },
  layerHeader: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "6px",
  },
  layerTitleButton: {
    minWidth: 0,
    padding: 0,
    overflow: "hidden",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.colorTextEmphasis,
    cursor: "pointer",
    fontSize: "10px",
    fontWeight: 700,
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  layerActions: { display: "flex", alignItems: "center", gap: "2px" },
  iconButton: {
    width: "24px",
    height: "24px",
    display: "grid",
    placeItems: "center",
    padding: 0,
    borderWidth: 0,
    borderRadius: "6px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: {
      default: tokens.colorMuted,
      ":disabled": tokens.colorTextDisabled,
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
  },
  controls: { display: "grid", gap: "7px" },
  controlGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "6px 8px",
  },
  control: {
    minWidth: 0,
    display: "grid",
    gap: "3px",
    color: tokens.colorSubtle,
    fontSize: "9px",
  },
  controlWide: { gridColumn: "1 / -1" },
  controlInput: {
    width: "100%",
    minWidth: 0,
    height: "25px",
    paddingInline: "6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    backgroundColor: tokens.colorSurface,
    color: tokens.colorText,
    fontFamily: MONO,
    fontSize: "9px",
  },
  colorInput: { padding: "2px" },
  rangeRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 34px",
    alignItems: "center",
    gap: "5px",
  },
  range: { width: "100%", accentColor: tokens.colorAccent },
  rangeValue: {
    color: tokens.colorText,
    fontFamily: MONO,
    fontSize: "9px",
    textAlign: "right",
  },
  section: {
    display: "grid",
    gap: "5px",
    paddingTop: "5px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
  },
  sectionTitle: {
    color: tokens.colorMuted,
    fontSize: "9px",
    fontWeight: 750,
  },
  toggle: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    color: tokens.colorText,
    fontSize: "9px",
  },
  categoryList: {
    display: "grid",
    gap: "4px",
  },
  categoryRow: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "16px 22px minmax(0, 1fr) 48px",
    alignItems: "center",
    gap: "6px",
    paddingBlock: "3px",
    color: tokens.colorText,
    fontSize: "9px",
  },
  categoryColor: {
    width: "22px",
    height: "18px",
    padding: "1px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "4px",
    backgroundColor: "transparent",
    cursor: "pointer",
  },
  categoryRadius: {
    width: "48px",
    minWidth: 0,
    height: "22px",
    paddingInline: "4px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "4px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    backgroundColor: tokens.colorSurface,
    color: tokens.colorText,
    fontFamily: MONO,
    fontSize: "8px",
  },
  categoryText: {
    minWidth: 0,
    display: "grid",
    gap: "1px",
  },
  categoryTitle: {
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontWeight: 700,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  categoryMeta: {
    overflow: "hidden",
    color: tokens.colorMuted,
    fontFamily: MONO,
    fontSize: "8px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resetButton: {
    minHeight: "25px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "5px",
    paddingInline: "8px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    backgroundColor: tokens.colorSurface,
    color: tokens.colorText,
    cursor: "pointer",
    fontSize: "9px",
  },
  featurePanel: {
    position: "absolute",
    right: "10px",
    bottom: "30px",
    zIndex: 3,
    width: "min(292px, calc(100% - 20px))",
    maxHeight: "min(280px, calc(100% - 82px))",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    borderRadius: "10px",
    backgroundColor: "light-dark(rgba(255,255,255,.97), rgba(20,24,32,.97))",
    boxShadow: tokens.shadowNodeRaised,
    backdropFilter: "blur(14px)",
  },
  featureHeader: {
    minWidth: 0,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "8px",
    padding: "10px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  featureHeading: {
    minWidth: 0,
    display: "grid",
    gap: "2px",
  },
  featureKicker: {
    overflow: "hidden",
    color: tokens.colorMuted,
    fontSize: "9px",
    fontWeight: 750,
    letterSpacing: "0.04em",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  featureTitle: {
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 750,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  featureMeta: {
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
  },
  featureProperties: {
    minHeight: 0,
    display: "grid",
    gap: "1px",
    margin: 0,
    overflowY: "auto",
    padding: "6px 10px 10px",
  },
  featureProperty: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "minmax(72px, .75fr) minmax(0, 1.25fr)",
    gap: "8px",
    paddingBlock: "5px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  featurePropertyName: {
    minWidth: 0,
    overflow: "hidden",
    color: tokens.colorMuted,
    fontFamily: MONO,
    fontSize: "9px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  featurePropertyValue: {
    minWidth: 0,
    margin: 0,
    overflowWrap: "anywhere",
    color: tokens.colorText,
    fontFamily: MONO,
    fontSize: "9px",
    lineHeight: 1.45,
  },
  featureEmpty: {
    margin: 0,
    padding: "10px",
    color: tokens.colorSubtle,
    fontSize: "10px",
  },
  rawShell: { display: "grid", gap: "7px" },
  rawHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
  },
  rawMeta: { color: tokens.colorSubtle, fontSize: "10px" },
  raw: {
    margin: 0,
    fontFamily: MONO,
    fontSize: "10px",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
});
