import * as stylex from "@stylexjs/stylex";

import { tokens } from "@/lib/stylex/tokens.stylex";

export const styles = stylex.create({
  header: {
    display: "grid",
    gridTemplateColumns: {
      default: "132px minmax(0, 1fr)",
      "@media (max-width: 720px)": "1fr",
    },
    alignItems: "center",
    gap: "12px",
    padding: {
      default: "12px 48px 12px 16px",
      "@media (max-width: 720px)": "12px 48px 12px 12px",
    },
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
  },
  heading: { minWidth: 0 },
  titleRow: { display: "flex", alignItems: "center", gap: "9px" },
  title: {
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeLg,
    fontWeight: 760,
  },
  description: {
    marginTop: "3px",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeSm,
  },
  searchWrap: { position: "relative" },
  searchIcon: {
    position: "absolute",
    top: "11px",
    left: "12px",
    color: tokens.colorSubtle,
    pointerEvents: "none",
  },
  search: {
    width: "100%",
    height: {
      default: "40px",
      "@media (max-width: 720px)": "44px",
    },
    padding: "0 12px 0 34px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: tokens.colorBorderStrong,
      ":focus": tokens.colorAccent,
    },
    borderRadius: tokens.radiusSm,
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "2px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    backgroundColor: tokens.colorSurfaceSunken,
    color: tokens.colorText,
    fontSize: tokens.fontSizeSm,
  },
  layout: {
    minHeight: 0,
    flex: 1,
    display: "grid",
    overflow: "hidden",
    overscrollBehaviorY: "contain",
    paddingBottom: {
      default: 0,
      "@media (max-width: 720px)": "env(safe-area-inset-bottom, 0px)",
    },
    gridTemplateColumns: {
      default: "148px minmax(0, 1fr) 360px",
      "@media (max-width: 1024px)": "minmax(0, 1fr) minmax(0, 1fr)",
      "@media (max-width: 720px)": "1fr",
    },
    gridTemplateRows: {
      default: "minmax(0, 1fr)",
      "@media (max-width: 1024px)": "auto minmax(0, 1fr)",
    },
    gridTemplateAreas: {
      default: '"filters nodes inspector"',
      "@media (max-width: 1024px)": '"filters filters" "nodes inspector"',
      "@media (max-width: 720px)": '"filters" "nodes"',
    },
  },
  detailLayout: {
    gridTemplateColumns: "minmax(0, 1fr)",
    gridTemplateRows: "minmax(0, 1fr)",
    gridTemplateAreas: '"inspector"',
  },
  hidden: { display: "none" },
  compactFilters: {
    display: { default: "none", "@media (max-width: 1024px)": "flex" },
    alignItems: "center",
    gap: "8px",
  },
  sourceRail: {
    display: { default: "block", "@media (max-width: 1024px)": "none" },
  },
  filterButton: {
    minHeight: "44px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    flexShrink: 0,
    paddingInline: "10px",
    border: `1px solid ${tokens.colorBorderStrong}`,
    borderRadius: tokens.radiusSm,
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: tokens.colorText,
    fontSize: tokens.fontSizeSm,
    cursor: "pointer",
  },
  refinementsCollapsed: {
    display: { default: "grid", "@media (max-width: 1024px)": "none" },
  },
  backButton: {
    minHeight: "44px",
    display: "inline-flex",
    alignItems: "center",
    alignSelf: "flex-start",
    flexShrink: 0,
    gap: "6px",
    paddingInline: "12px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.colorText,
    fontSize: tokens.fontSizeSm,
    cursor: "pointer",
  },
  originBadge: {
    minHeight: "17px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    paddingInline: "5px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorderStrong,
    borderRadius: "99px",
    backgroundColor: tokens.colorSurfaceSunken,
    color: tokens.colorMuted,
    fontSize: "8px",
    fontWeight: 840,
    letterSpacing: "0.06em",
    lineHeight: 1,
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  filterPane: {
    gridArea: "filters",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    padding: {
      default: "12px 8px",
      "@media (max-width: 1024px)": "6px 12px",
    },
    borderRightWidth: {
      default: 1,
      "@media (max-width: 1024px)": 0,
    },
    borderRightStyle: "solid",
    borderRightColor: tokens.colorBorder,
    borderBottomWidth: {
      default: 0,
      "@media (max-width: 1024px)": 1,
    },
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
    overflowY: "auto",
  },
  filterHeading: {
    paddingInline: "10px",
    marginBottom: {
      default: "10px",
      "@media (max-width: 720px)": 0,
    },
    flexShrink: 0,
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeXs,
    fontWeight: 730,
  },
  filterLibrary: {
    marginTop: {
      default: "12px",
      "@media (max-width: 720px)": 0,
    },
    paddingTop: {
      default: "12px",
      "@media (max-width: 720px)": 0,
    },
    borderTopWidth: {
      default: 1,
      "@media (max-width: 720px)": 0,
    },
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
  },
  refinementSection: {
    marginTop: {
      default: "12px",
      "@media (max-width: 720px)": 0,
    },
    paddingTop: {
      default: "12px",
      "@media (max-width: 720px)": 0,
    },
    borderTopWidth: {
      default: 1,
      "@media (max-width: 720px)": 0,
    },
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
    display: "grid",
    gap: "10px",
    paddingInline: "10px",
  },
  refinementField: {
    display: "grid",
    gap: "4px",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    fontWeight: 730,
  },
  refinementSelect: {
    width: "100%",
    minHeight: { default: "32px", "@media (max-width: 1024px)": "44px" },
    padding: "0 8px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorderStrong,
    borderRadius: tokens.radiusSm,
    backgroundColor: tokens.colorSurfaceSunken,
    color: tokens.colorText,
    fontSize: tokens.fontSizeSm,
    cursor: "pointer",
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "2px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
  },
  refinementCheck: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    fontWeight: 640,
    cursor: "pointer",
    minHeight: { default: "24px", "@media (max-width: 1024px)": "44px" },
  },
  nodePane: {
    gridArea: "nodes",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    borderRightWidth: {
      default: 1,
      "@media (max-width: 720px)": 0,
    },
    borderRightStyle: "solid",
    borderRightColor: tokens.colorBorder,
  },
  nodePaneHeader: {
    display: "grid",
    padding: "10px 14px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
  },
  nodePaneTitle: {
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 730,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resultCount: {
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    whiteSpace: "nowrap",
  },
  resultHeading: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "12px",
  },
  categoryToolbar: {
    display: {
      default: "grid",
      "@media (max-width: 720px)": "flex",
    },
    flexDirection: "row",
    width: {
      default: "auto",
      "@media (max-width: 720px)": "max-content",
    },
    gap: "2px",
  },
  categoryButton: {
    width: {
      default: "100%",
      "@media (max-width: 720px)": "auto",
    },
    minHeight: {
      default: "36px",
      "@media (max-width: 720px)": "44px",
    },
    display: "flex",
    alignItems: "center",
    gap: "10px",
    paddingInline: "10px",
    borderWidth: 0,
    borderRadius: tokens.radiusSm,
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "1px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: tokens.colorSubtle,
    cursor: "pointer",
    fontSize: tokens.fontSizeSm,
    fontWeight: 560,
    textAlign: "left",
    whiteSpace: "nowrap",
  },
  categoryButtonActive: {
    backgroundColor: tokens.colorSurfaceRaised,
    color: tokens.colorTextEmphasis,
  },
  compatibilityBanner: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "7px 12px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurfaceMuted,
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeXs,
  },
  nodeList: {
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    padding: "6px",
  },
  nodeRow: {
    width: "100%",
    minHeight: "56px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    padding: "9px 10px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: "transparent",
      ":hover": tokens.colorBorderStrong,
    },
    borderRadius: "8px",
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: tokens.colorText,
    cursor: "pointer",
    fontFamily: "inherit",
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "-3px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    textAlign: "left",
    transitionProperty: "background-color, border-color",
    transitionDuration: "120ms",
  },
  nodeRowActive: {
    borderColor: tokens.colorAccent,
    backgroundColor: tokens.colorAccentSoft,
  },
  nodeCopy: { minWidth: 0, display: "grid", gap: "3px" },
  nodeTitleRow: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  nodeTitle: {
    minWidth: 0,
    overflow: "hidden",
    fontSize: tokens.fontSizeSm,
    fontWeight: 730,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  nodeDescription: {
    display: "-webkit-box",
    overflow: "hidden",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    lineHeight: 1.4,
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 1,
  },
  technicalToggle: {
    minHeight: { default: "28px", "@media (max-width: 720px)": "44px" },
    alignSelf: "flex-start",
    paddingInline: "0",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.colorMuted,
    cursor: "pointer",
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "2px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    fontSize: tokens.fontSizeXs,
    fontWeight: 680,
    textDecorationLine: "underline",
    textUnderlineOffset: "2px",
  },
  empty: {
    minHeight: "160px",
    display: "grid",
    placeItems: "center",
    alignContent: "center",
    gap: "10px",
    padding: "24px",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeSm,
    lineHeight: 1.5,
    textAlign: "center",
  },
  moduleDiagnostics: {
    display: "grid",
    gap: "8px",
    padding: "12px 14px 16px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
    backgroundColor: tokens.colorSurfaceMuted,
  },
  moduleDiagnosticsNote: {
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    lineHeight: 1.45,
  },
  openGraphButton: {
    flexShrink: 0,
    minHeight: "24px",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    paddingInline: "7px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorderStrong,
    borderRadius: "5px",
    backgroundColor: {
      default: tokens.colorSurface,
      ":hover": tokens.colorHover,
    },
    color: tokens.colorMuted,
    cursor: "pointer",
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "2px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    fontSize: "10px",
    fontWeight: 700,
  },
  inspectorOpenGraph: {
    marginTop: "8px",
    alignSelf: "flex-start",
  },
  resetButton: {
    minHeight: "29px",
    paddingInline: "10px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorderStrong,
    borderRadius: "5px",
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: tokens.colorMuted,
    cursor: "pointer",
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "2px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    fontSize: tokens.fontSizeXs,
    fontWeight: 700,
  },
  inspector: {
    gridArea: "inspector",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    backgroundColor: tokens.colorSurface,
  },
  inspectorBody: {
    minHeight: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  previewStage: {
    flexShrink: 0,
    maxHeight: "36%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "14px 12px",
    overflow: "auto",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
  },
  inspectorScroll: { minHeight: 0, flex: 1, overflowY: "auto" },
  inspectorHeader: {
    padding: "14px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
  },
  inspectorProvenance: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
  },
  eyebrow: {
    color: tokens.colorAccent,
    fontSize: "10px",
    fontWeight: 820,
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  inspectorTitle: {
    marginTop: 0,
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeLg,
    fontWeight: 760,
    letterSpacing: "-0.015em",
    lineHeight: 1.2,
  },
  operatorId: {
    marginTop: "5px",
    color: tokens.colorSubtle,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: tokens.fontSizeXs,
  },
  inspectorDescription: {
    maxWidth: "68ch",
    marginTop: "10px",
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeSm,
    lineHeight: 1.55,
  },
  inspectorSummary: {
    display: "grid",
    gap: "8px",
    marginTop: "12px",
  },
  inspectorStatement: {
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeSm,
    lineHeight: 1.5,
  },
  inspectorStatementStrong: {
    color: tokens.colorTextEmphasis,
    fontWeight: 680,
  },
  inspectorConfiguration: {
    display: "grid",
    gap: "3px",
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeSm,
    lineHeight: 1.5,
  },
  inspectorConfigurationLabel: {
    color: tokens.colorTextEmphasis,
    fontWeight: 680,
  },
  section: {
    padding: "18px 22px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
  },
  sectionTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    marginBottom: "12px",
  },
  sectionIcon: { color: tokens.colorSubtle },
  sectionTitle: {
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 750,
  },
  worksWithHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
    marginBottom: "12px",
  },
  worksWithTitle: {
    flexShrink: 0,
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 750,
  },
  worksWithPort: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontFamily: "inherit",
    fontSize: tokens.fontSizeSm,
    fontWeight: 650,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  worksWithPortSelect: {
    padding: "1px 0",
    borderWidth: 0,
    borderBottomWidth: 1,
    borderStyle: "solid",
    borderBottomColor: tokens.colorBorderStrong,
    borderRadius: 0,
    backgroundColor: "transparent",
    cursor: "pointer",
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "2px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
  },
  compatibilityHeading: {
    marginBottom: "5px",
    color: tokens.colorSubtle,
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.09em",
    textTransform: "uppercase",
  },
  compatibilityList: { display: "grid" },
  compatibilityItem: {
    width: "100%",
    display: "grid",
    gap: "2px",
    padding: "8px 0",
    borderWidth: 0,
    borderBottomWidth: 1,
    borderStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: tokens.colorText,
    cursor: "pointer",
    fontFamily: "inherit",
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "2px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    textAlign: "left",
  },
  compatibilityName: {
    overflow: "hidden",
    color: tokens.colorText,
    fontSize: tokens.fontSizeSm,
    fontWeight: 680,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  compatibilityMeta: {
    overflow: "hidden",
    color: tokens.colorSubtle,
    fontSize: "10px",
    lineHeight: 1.4,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  compatibilityEmpty: {
    padding: "8px 0",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    lineHeight: 1.45,
  },
  portGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 900px)": "1fr",
    },
    gap: "18px",
  },
  portColumnHeading: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginBottom: "5px",
    color: tokens.colorSubtle,
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.09em",
    textTransform: "uppercase",
  },
  portList: { display: "grid" },
  portRow: {
    display: "grid",
    gridTemplateColumns: "7px minmax(0, 1fr)",
    gap: "9px",
    padding: "10px 0",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  portDot: {
    width: "7px",
    height: "7px",
    marginTop: "5px",
    borderRadius: "99px",
  },
  portCopy: { minWidth: 0 },
  portTitle: {
    color: tokens.colorText,
    fontSize: tokens.fontSizeSm,
    fontWeight: 690,
  },
  portContract: {
    marginTop: "2px",
    overflow: "hidden",
    color: tokens.colorSubtle,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  portRules: {
    marginTop: "3px",
    color: tokens.colorSubtle,
    fontSize: "10px",
  },
  portDescription: {
    marginTop: "5px",
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeXs,
    lineHeight: 1.45,
  },
  fieldList: { display: "grid" },
  fieldRow: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(130px, 0.7fr) minmax(0, 1.3fr)",
      "@media (max-width: 900px)": "1fr",
    },
    gap: "8px 18px",
    padding: "11px 0",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  fieldIdentity: { minWidth: 0 },
  fieldTitle: {
    color: tokens.colorText,
    fontSize: tokens.fontSizeSm,
    fontWeight: 690,
  },
  fieldName: {
    marginTop: "2px",
    overflow: "hidden",
    color: tokens.colorSubtle,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fieldDetails: { minWidth: 0 },
  fieldMeta: { color: tokens.colorSubtle, fontSize: "10px" },
  fieldDescription: {
    marginTop: "4px",
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeXs,
    lineHeight: 1.45,
  },
  fieldChoices: {
    marginTop: "4px",
    overflowWrap: "anywhere",
    color: tokens.colorSubtle,
    fontSize: "10px",
  },
  inspectorFooter: {
    minHeight: "62px",
    display: "grid",
    padding: "10px 18px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
    backgroundColor: tokens.colorSurfaceRaised,
  },
  visuallyHidden: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
  addButton: {
    width: "100%",
    minHeight: "44px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "7px",
    paddingInline: "12px",
    overflow: "hidden",
    borderWidth: 0,
    borderRadius: tokens.radiusSm,
    backgroundColor: {
      default: tokens.colorAccent,
      ":hover": tokens.colorAccentHover,
    },
    color: tokens.colorOnAccent,
    cursor: "pointer",
    outlineColor: tokens.colorAccent,
    outlineStyle: "solid",
    outlineOffset: "2px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    fontSize: tokens.fontSizeSm,
    fontWeight: 750,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  addButtonDisabled: {
    backgroundColor: tokens.colorAccentDisabled,
    color: tokens.colorTextDisabled,
    cursor: "not-allowed",
  },
});
