import re

MAX_TEXT_CHARS = 200_000
MAX_QUESTIONS = 128
MAX_CHOICE_OPTIONS = 255
MIN_SCORE_LEVELS = 2
MAX_SCORE_LEVELS = 10
MAX_QUESTION_ID_LENGTH = 128
MAX_OPTION_LABEL_LENGTH = 256

QUESTION_ID_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*$")
DEFAULT_BASE_URL = "https://api.typesafe.ai"
DEFAULT_MODEL = "jev-latest"
