import * as stylex from "@stylexjs/stylex";

import { tokens } from "@/lib/stylex/tokens.stylex";

const MONO = "ui-monospace, SFMono-Regular, Menlo, monospace";

export const executionHistoryDrawerStyles = stylex.create({
  drawer: {
    position: "absolute",
    zIndex: 35,
    top: {
      default: "66px",
      "@media (max-width: 720px)": "12px",
      "@media (max-width: 620px)":
        "calc(var(--grafy-mobile-overlay-top, 68px) + env(safe-area-inset-top, 0px))",
    },
    right: {
      default: "13px",
      "@media (max-width: 720px)":
        "calc(12px + env(safe-area-inset-right, 0px))",
    },
    bottom: {
      default: "12px",
      "@media (max-width: 720px)":
        "calc(12px + env(safe-area-inset-bottom, 0px))",
    },
    left: {
      default: "auto",
      "@media (max-width: 720px)":
        "calc(12px + env(safe-area-inset-left, 0px))",
    },
    width: {
      default: "min(880px, calc(100% - 26px))",
      "@media (max-width: 720px)": "auto",
    },
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorderStrong,
    borderRadius: "12px",
    backgroundColor: tokens.colorSurface,
    boxShadow: tokens.shadowNodeSelected,
    color: tokens.colorText,
  },
  header: {
    minHeight: "52px",
    display: "flex",
    alignItems: "center",
    gap: "9px",
    padding: "8px 9px 8px 14px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
  },
  headerIcon: {
    width: "28px",
    height: "28px",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    borderRadius: "8px",
    backgroundColor: tokens.colorAccentSoft,
    color: tokens.colorAccent,
  },
  headerCopy: { minWidth: 0, flex: 1, display: "grid", gap: "1px" },
  title: {
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeMd,
    fontWeight: 760,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  subtitle: {
    overflow: "hidden",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerButton: {
    width: {
      default: "30px",
      "@media (max-width: 720px)": "44px",
    },
    height: {
      default: "30px",
      "@media (max-width: 720px)": "44px",
    },
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    borderWidth: 0,
    borderRadius: "7px",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorHover,
      ":disabled": "transparent",
    },
    color: {
      default: tokens.colorMuted,
      ":disabled": tokens.colorTextDisabled,
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
  },
  dirtyWarning: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 14px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorBorder,
    backgroundColor:
      "light-dark(rgba(201, 146, 15, 0.09), rgba(251, 191, 36, 0.1))",
    color: tokens.colorWarning,
    fontSize: tokens.fontSizeXs,
    lineHeight: 1.45,
  },
  content: {
    minHeight: 0,
    flex: 1,
    display: "grid",
    gridTemplateColumns: {
      default: "300px minmax(0, 1fr)",
      "@media (max-width: 720px)": "1fr",
    },
    gridTemplateRows: {
      default: "minmax(0, 1fr)",
      "@media (max-width: 720px)": "minmax(180px, 0.8fr) minmax(0, 1.2fr)",
    },
  },
  listPane: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    borderRightWidth: {
      default: 1,
      "@media (max-width: 720px)": 0,
    },
    borderRightStyle: "solid",
    borderRightColor: tokens.colorBorder,
  },
  list: { minHeight: 0, flex: 1, overflowY: "auto", padding: "5px" },
  listItem: {
    width: "100%",
    minHeight: "82px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 16px",
    alignItems: "center",
    gap: "7px",
    padding: "9px 8px 9px 10px",
    borderWidth: 0,
    borderRadius: "8px",
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: tokens.colorText,
    cursor: "pointer",
    textAlign: "left",
  },
  listItemSelected: {
    backgroundColor: {
      default: tokens.colorAccentSoft,
      ":hover": tokens.colorAccentSoft,
    },
  },
  listCopy: { minWidth: 0, display: "grid", gap: "5px" },
  listTop: { display: "flex", alignItems: "center", gap: "6px" },
  timestamp: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 690,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  status: {
    flexShrink: 0,
    padding: "2px 6px",
    borderRadius: "9999px",
    backgroundColor: tokens.colorSurfaceMuted,
    color: tokens.colorMuted,
    fontSize: "9px",
    fontWeight: 780,
    letterSpacing: "0.03em",
    textTransform: "uppercase",
  },
  statusSuccess: {
    backgroundColor:
      "light-dark(rgba(42, 157, 124, 0.11), rgba(67, 197, 158, 0.14))",
    color: tokens.colorSuccess,
  },
  statusFailure: {
    backgroundColor: tokens.colorDangerHover,
    color: tokens.colorDanger,
  },
  statusActive: {
    backgroundColor: tokens.colorAccentSoft,
    color: tokens.colorAccent,
  },
  statusCancelled: {
    backgroundColor:
      "light-dark(rgba(201, 146, 15, 0.12), rgba(251, 191, 36, 0.15))",
    color: tokens.colorWarning,
  },
  meta: {
    color: tokens.colorSubtle,
    fontSize: "10px",
    lineHeight: 1.35,
  },
  id: {
    overflow: "hidden",
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  loadMoreWrap: {
    padding: "7px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
  },
  loadMore: {
    width: "100%",
    height: {
      default: "31px",
      "@media (max-width: 720px)": "44px",
    },
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    borderRadius: "7px",
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: tokens.colorMuted,
    cursor: "pointer",
    fontSize: tokens.fontSizeXs,
    fontWeight: 700,
  },
  detailPane: {
    minHeight: 0,
    overflowY: "auto",
    padding: {
      default: "14px",
      "@media (max-width: 720px)": "12px",
    },
    borderTopWidth: {
      default: 0,
      "@media (max-width: 720px)": 1,
    },
    borderTopStyle: "solid",
    borderTopColor: tokens.colorBorder,
  },
  detailHeader: {
    display: "grid",
    gap: "7px",
    marginBottom: "14px",
    paddingBottom: "12px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  detailHeading: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "7px",
  },
  detailTitle: { fontSize: "15px", fontWeight: 760 },
  detailMeta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "5px 10px",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeXs,
  },
  nodeList: { display: "grid", gap: "12px" },
  nodeResult: {
    display: "grid",
    gap: "10px",
    padding: "11px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    borderRadius: "10px",
    backgroundColor: tokens.colorSurfaceRaised,
  },
  nodeHead: { display: "flex", alignItems: "center", gap: "7px" },
  nodePosition: {
    width: "22px",
    height: "22px",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    borderRadius: "6px",
    backgroundColor: tokens.colorSurfaceMuted,
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
  },
  nodeCopy: { minWidth: 0, flex: 1, display: "grid", gap: "1px" },
  nodeTitle: {
    overflow: "hidden",
    fontSize: tokens.fontSizeSm,
    fontWeight: 720,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  nodeId: {
    overflow: "hidden",
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  nodeError: {
    margin: 0,
    padding: "7px 8px",
    borderRadius: "6px",
    backgroundColor: tokens.colorDangerHover,
    color: tokens.colorDanger,
    fontSize: tokens.fontSizeXs,
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
  },
  outputList: { display: "grid", gap: "12px" },
  unavailableOutput: {
    display: "grid",
    gap: "5px",
    padding: "9px 10px",
    borderRadius: "8px",
    backgroundColor: tokens.colorSurfaceMuted,
  },
  unavailablePort: {
    color: tokens.colorMuted,
    fontFamily: MONO,
    fontSize: "10px",
    fontWeight: 750,
  },
  message: {
    minHeight: "150px",
    display: "grid",
    placeItems: "center",
    alignContent: "center",
    gap: "8px",
    padding: "28px 18px",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeSm,
    lineHeight: 1.5,
    textAlign: "center",
  },
  messageError: { color: tokens.colorDanger },
  retry: {
    height: "29px",
    paddingInline: "10px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorderStrong,
    borderRadius: "7px",
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: tokens.colorMuted,
    cursor: "pointer",
    fontSize: tokens.fontSizeXs,
    fontWeight: 700,
  },
  spinner: {
    animationName: "grafy-spin",
    animationDuration: "900ms",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
});
