import type { NodeRegistry } from "../src/lib/api/contract";

const pythonNode = {
  origin: "plugin",
  operator_id: "python.transform",
  operator_version: 1,
  plugin_slug: "external.python",
  title: "Python",
  description:
    "Runs applied Python code on one input. Transforms must be deterministic.",
  config_schema: {},
  input_schema: {},
  output_schema: {},
  inputs: [
    {
      name: "input",
      title: null,
      description: "The value passed to the data parameter of transform.",
      direction: "input",
      artifact_type: null,
      artifact_type_variable: "input",
      also_accepts: [],
      shape: "one",
      accepted_shapes: ["one", "many"],
      instance_plugs: false,
      variadic: false,
      required: true,
      shape_field: "input_shape",
    },
  ],
  outputs: [
    {
      name: "output",
      title: null,
      description: "The value transform returns.",
      direction: "output",
      artifact_type: null,
      artifact_type_variable: "output",
      also_accepts: [],
      shape: "one",
      accepted_shapes: ["one"],
      instance_plugs: false,
      variadic: false,
      required: true,
      shape_field: "output_shape",
    },
  ],
  secret_inputs: [],
  module_graph_id: null,
  module_graph_revision: null,
  module_id: null,
  publication_state: null,
  is_current_library_release: null,
  catalog_visible: false,
  plugin_revision: 1,
  plugin_release: {
    scope: "system",
    slug: "external.python",
    revision: 1,
  },
  runnable: true,
  non_runnable_reason: null,
  non_runnable_detail: null,
} satisfies NodeRegistry["nodes"][number];

export const pythonCatalog = {
  nodes: [pythonNode],
  plugins: [
    {
      slug: "external.python",
      title: "Python",
      origin: "plugin",
      entry_kind: "plugin",
      scope: "system",
      plugin_release: { scope: "system", slug: "external.python", revision: 1 },
      revision: 1,
      publisher: "test:system",
      installation_scope: "system",
      runnable: true,
      non_runnable_reason: null,
      non_runnable_detail: null,
    },
  ],
  artifact_types: [
    {
      key: { id: "scalar.text", schema_version: 1 },
      title: "Text value",
      payload_schema: {
        additionalProperties: false,
        properties: { value: { title: "Value", type: "string" } },
        required: ["value"],
        title: "TextValue",
        type: "object",
      },
      field_projections: [],
      materialized_json_type: "string",
      export_formats: [
        {
          format: "txt",
          content_type: "text/plain; charset=utf-8",
          filename: "text.txt",
        },
      ],
      extensions: [],
      confirmation_rule: { rule: "none", signatures: [] },
      bundle: { format: "inline-json", version: 1 },
    },
    {
      key: { id: "scalar.integer", schema_version: 1 },
      title: "Integer value",
      payload_schema: {
        additionalProperties: false,
        properties: { value: { title: "Value", type: "integer" } },
        required: ["value"],
        title: "IntegerValuePayload",
        type: "object",
      },
      field_projections: [],
      materialized_json_type: "integer",
      export_formats: [],
      extensions: [],
      confirmation_rule: { rule: "none", signatures: [] },
      bundle: { format: "inline-json", version: 1 },
    },
    {
      key: { id: "text.markdown", schema_version: 1 },
      title: "Markdown",
      payload_schema: {
        additionalProperties: false,
        properties: { markdown: { title: "Markdown", type: "string" } },
        required: ["markdown"],
        title: "MarkdownValue",
        type: "object",
      },
      field_projections: [],
      materialized_json_type: null,
      export_formats: [
        {
          format: "txt",
          content_type: "text/plain; charset=utf-8",
          filename: "markdown.txt",
        },
      ],
      extensions: [],
      confirmation_rule: { rule: "none", signatures: [] },
      bundle: { format: "inline-json", version: 1 },
    },
    {
      key: { id: "table.data", schema_version: 1 },
      title: "Table",
      payload_schema: {
        $defs: {
          TableColumn: {
            additionalProperties: false,
            properties: {
              id: { maxLength: 255, minLength: 1, title: "Id", type: "string" },
              title: { maxLength: 1024, title: "Title", type: "string" },
              value_type: {
                $ref: "#/$defs/TableValueType",
                default: "unknown",
              },
            },
            required: ["id", "title"],
            title: "TableColumn",
            type: "object",
          },
          TableValue: {
            anyOf: [
              { type: "string" },
              { type: "integer" },
              { type: "number" },
              { type: "boolean" },
              { items: { $ref: "#/$defs/TableValue" }, type: "array" },
              {
                additionalProperties: { $ref: "#/$defs/TableValue" },
                type: "object",
              },
              { type: "null" },
            ],
          },
          TableValueType: {
            enum: [
              "text",
              "integer",
              "number",
              "decimal",
              "boolean",
              "date",
              "datetime",
              "json",
              "binary",
              "unknown",
              "mixed",
            ],
            title: "TableValueType",
            type: "string",
          },
        },
        additionalProperties: false,
        properties: {
          columns: {
            items: { $ref: "#/$defs/TableColumn" },
            maxItems: 10000,
            title: "Columns",
            type: "array",
          },
          rows: {
            items: {
              additionalProperties: { $ref: "#/$defs/TableValue" },
              type: "object",
            },
            title: "Rows",
            type: "array",
          },
        },
        required: ["columns", "rows"],
        title: "Table",
        type: "object",
      },
      field_projections: [],
      materialized_json_type: null,
      export_formats: [
        {
          format: "csv",
          content_type: "text/csv; charset=utf-8",
          filename: "table.csv",
        },
      ],
      extensions: [],
      confirmation_rule: { rule: "none", signatures: [] },
      bundle: { format: "table-bundle", version: 1 },
    },
  ],
  presets: [
    {
      id: "as-markdown",
      version: 1,
      config: {
        code: "def transform(text: str, context: Context) -> Markdown:\n    return Markdown(markdown=text)\n",
        code_sha256:
          "ebeb02b2b83ec43bccf1688f72518e0129eb3f54ccfbe5ff633dccb1991365b8",
        input_shape: "one",
        output_shape: "one",
        params_schema: null,
        params: {},
        preset_id: "as-markdown",
        preset_version: 1,
      },
      artifact_type_bindings: [
        {
          variable: "input",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
        {
          variable: "output",
          artifact_type: {
            id: "text.markdown",
            schema_version: 1,
          },
        },
      ],
      node: {
        ...pythonNode,
        title: "As Markdown",
        description: "Marks text as Markdown without transforming its source.",
        inputs: [
          {
            name: "input",
            title: null,
            description: "The value passed to the data parameter of transform.",
            direction: "input",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "one",
            accepted_shapes: ["one"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "input_shape",
          },
        ],
        outputs: [
          {
            name: "output",
            title: null,
            description: "The value transform returns.",
            direction: "output",
            artifact_type: { id: "text.markdown", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "one",
            accepted_shapes: ["one"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "output_shape",
          },
        ],
        catalog_visible: true,
      },
    },
    {
      id: "join-text",
      version: 1,
      config: {
        code: 'class Params(BaseModel):\n    separator: str = Field("", description="Text inserted between adjacent parts.")\n\n\ndef transform(parts: list[str], params: Params, context: Context) -> str:\n    return params.separator.join(parts)\n',
        code_sha256:
          "158f0a3bf9c1e2ea3cd055247faf505e0d2fa47fa36cdc061bd4e8580be1672e",
        input_shape: "many",
        output_shape: "one",
        params_schema: {
          title: "Params",
          type: "object",
          properties: {
            separator: {
              title: "Separator",
              type: "string",
              default: "",
              description: "Text inserted between adjacent parts.",
            },
          },
        },
        params: {
          separator: "",
        },
        preset_id: "join-text",
        preset_version: 1,
      },
      artifact_type_bindings: [
        {
          variable: "input",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
        {
          variable: "output",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
      ],
      node: {
        ...pythonNode,
        title: "Join text",
        description: "Joins an ordered text sequence with a separator.",
        inputs: [
          {
            name: "input",
            title: null,
            description: "The value passed to the data parameter of transform.",
            direction: "input",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "many",
            accepted_shapes: ["many"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "input_shape",
          },
        ],
        outputs: [
          {
            name: "output",
            title: null,
            description: "The value transform returns.",
            direction: "output",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "one",
            accepted_shapes: ["one"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "output_shape",
          },
        ],
        catalog_visible: true,
      },
    },
    {
      id: "python",
      version: 1,
      config: {
        code: "# One data input and one output, typed by their annotations: str, int,\n# Markdown, or list[...] of one of them. For settings shown as a form, add\n# `class Params(BaseModel)` and a `params: Params` parameter.\ndef transform(text: str, context: Context) -> str:\n    return text\n",
        code_sha256:
          "432ba95eaabe7a729dc84f9043810750ebcdcca99be3e07505afe642c6c80b47",
        input_shape: "one",
        output_shape: "one",
        params_schema: null,
        params: {},
        preset_id: "python",
        preset_version: 1,
      },
      artifact_type_bindings: [
        {
          variable: "input",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
        {
          variable: "output",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
      ],
      node: {
        ...pythonNode,
        title: "Python",
        description:
          "Runs your own Python code on one input to produce one output.",
        inputs: [
          {
            name: "input",
            title: null,
            description: "The value passed to the data parameter of transform.",
            direction: "input",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "one",
            accepted_shapes: ["one"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "input_shape",
          },
        ],
        outputs: [
          {
            name: "output",
            title: null,
            description: "The value transform returns.",
            direction: "output",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "one",
            accepted_shapes: ["one"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "output_shape",
          },
        ],
        catalog_visible: true,
      },
    },
    {
      id: "replace-text",
      version: 1,
      config: {
        code: 'class Params(BaseModel):\n    search: str = Field(min_length=1, description="Exact text to find.")\n    replacement: str = Field("", description="Text substituted for every match.")\n\n\ndef transform(text: str, params: Params, context: Context) -> str:\n    return text.replace(params.search, params.replacement)\n',
        code_sha256:
          "f2309c145ea2a8ab67fd6cdd3767960959e9825f11e40af0f422d872f43272f9",
        input_shape: "one",
        output_shape: "one",
        params_schema: {
          title: "Params",
          type: "object",
          required: ["search"],
          properties: {
            search: {
              title: "Search",
              type: "string",
              minLength: 1,
              description: "Exact text to find.",
            },
            replacement: {
              title: "Replacement",
              type: "string",
              default: "",
              description: "Text substituted for every match.",
            },
          },
        },
        params: {
          replacement: "",
        },
        preset_id: "replace-text",
        preset_version: 1,
      },
      artifact_type_bindings: [
        {
          variable: "input",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
        {
          variable: "output",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
      ],
      node: {
        ...pythonNode,
        title: "Replace text",
        description: "Replaces every exact occurrence of the search text.",
        inputs: [
          {
            name: "input",
            title: null,
            description: "The value passed to the data parameter of transform.",
            direction: "input",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "one",
            accepted_shapes: ["one"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "input_shape",
          },
        ],
        outputs: [
          {
            name: "output",
            title: null,
            description: "The value transform returns.",
            direction: "output",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "one",
            accepted_shapes: ["one"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "output_shape",
          },
        ],
        catalog_visible: true,
      },
    },
    {
      id: "split-text",
      version: 1,
      config: {
        code: 'class Params(BaseModel):\n    separator: str = Field(\n        min_length=1,\n        description="Exact text used to separate the input into parts.",\n    )\n\n\ndef transform(text: str, params: Params, context: Context) -> list[str]:\n    return text.split(params.separator)\n',
        code_sha256:
          "b338fde756b0f5b895bd91e001bec685594c52df54f2e0890d9429ce0dae9635",
        input_shape: "one",
        output_shape: "many",
        params_schema: {
          title: "Params",
          type: "object",
          required: ["separator"],
          properties: {
            separator: {
              title: "Separator",
              type: "string",
              minLength: 1,
              description: "Exact text used to separate the input into parts.",
            },
          },
        },
        params: {},
        preset_id: "split-text",
        preset_version: 1,
      },
      artifact_type_bindings: [
        {
          variable: "input",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
        {
          variable: "output",
          artifact_type: {
            id: "scalar.text",
            schema_version: 1,
          },
        },
      ],
      node: {
        ...pythonNode,
        title: "Split text",
        description:
          "Splits text on an exact separator while preserving empty parts.",
        inputs: [
          {
            name: "input",
            title: null,
            description: "The value passed to the data parameter of transform.",
            direction: "input",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "one",
            accepted_shapes: ["one"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "input_shape",
          },
        ],
        outputs: [
          {
            name: "output",
            title: null,
            description: "The value transform returns.",
            direction: "output",
            artifact_type: { id: "scalar.text", schema_version: 1 },
            artifact_type_variable: null,
            also_accepts: [],
            shape: "many",
            accepted_shapes: ["many"],
            instance_plugs: false,
            variadic: false,
            required: true,
            shape_field: "output_shape",
          },
        ],
        catalog_visible: true,
      },
    },
  ],
} satisfies Pick<
  NodeRegistry,
  "nodes" | "plugins" | "artifact_types" | "presets"
>;
