[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grafy-plugin-image"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "grafy-core==0.1.0",
    "pydantic",
]

[dependency-groups]
dev = ["pytest>=8.4.2", "pytest-asyncio>=1.3.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.grafy.plugin]
loader-target = "grafy_plugin_image.plugin:IMAGES"

[tool.basedpyright]
extends = "../../pyproject.toml"
venvPath = "."
venv = ".venv"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
