import * as stylex from "@stylexjs/stylex";

import { tokens } from "@/lib/stylex/tokens.stylex";

/** Style keys of the table artifact renderer and its parts. */
const MONO = "ui-monospace, SFMono-Regular, Menlo, monospace";

/**
 * A body row's tint, set on the `<tr>` and painted by each of its cells. The
 * sticky row number keeps an opaque surface under the tint, so cells that
 * scroll beneath it stay hidden on a hovered or selected row.
 */
const ROW_TINT = "--grafy-table-row-tint";
const ROW_TINT_LAYER = `linear-gradient(var(${ROW_TINT}, transparent), var(${ROW_TINT}, transparent))`;

/** Separates sticky headers from the rows and columns scrolled beneath them. */
const STICKY_EDGE_SHADOW_COLOR =
  "light-dark(rgba(17, 17, 17, 0.12), rgba(0, 0, 0, 0.55))";

/**
 * Sticky cells meet the scrollport on a fractional pixel at most canvas zoom
 * levels, so a sliver of the cells scrolled beneath them shows through. Each
 * sticky edge reaches past the scrollport, where the overflow clips it.
 */
const STICKY_COVER = {
  content: '""',
  position: "absolute",
  pointerEvents: "none",
  backgroundColor: "inherit",
  backgroundImage: "inherit",
} as const;

export const s = stylex.create({
  tablePreview: {
    display: "grid",
    gap: "6px",
    minWidth: 0,
  },
  tableCanvas: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    gap: 0,
    minHeight: 0,
  },
  tableCanvasLoading: {
    height: "100%",
    boxSizing: "border-box",
    padding: "16px",
    alignContent: "center",
    justifyItems: "center",
  },
  tableCanvasToolbar: {
    flexShrink: 0,
    flexWrap: "wrap",
    padding: "7px 10px",
    minHeight: "26px",
  },
  tableCanvasPager: {
    flexShrink: 0,
    flexWrap: "wrap",
    padding: "7px 18px 7px 10px",
  },
  // Wrapped onto its own line, the page buttons stay at the trailing edge.
  tableCanvasPagerActions: { marginLeft: "auto" },
  // Holds the rows and anything laid over them. As the preview's grid item it
  // must not take the table's width, or the rows would stop scrolling.
  tableStage: { position: "relative", minWidth: 0 },
  tableCanvasStage: {
    display: "flex",
    flexDirection: "column",
    flex: "1 1 auto",
    minHeight: 0,
  },
  tableCanvasViewport: {
    flex: "1 1 auto",
    minHeight: 0,
    maxHeight: "none",
  },
  // Covers the rows instead of squeezing them, so the value gets the room the
  // table had and the rows keep their scroll position underneath.
  tableCanvasCellDetail: {
    position: "absolute",
    inset: 0,
    zIndex: 4,
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: "8px",
    padding: "8px 10px 10px",
    borderRadius: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurface,
  },
  tableCanvasCellDetailValue: {
    height: "100%",
    minHeight: 0,
    resize: "none",
  },
  tableSummary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    color: tokens.colorMuted,
    fontSize: "10px",
  },
  tableSummaryMeta: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    whiteSpace: "nowrap",
  },
  tableSummaryStrong: {
    color: tokens.colorTextEmphasis,
    fontWeight: 700,
  },
  tableSummaryDivider: {
    color: tokens.colorDivider,
  },
  tableToolbarActions: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  tableViewport: {
    width: "100%",
    maxHeight: "420px",
    overflow: "auto",
    // Lets the empty state size itself to the visible width, not the table's.
    containerType: "inline-size",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  dataTable: {
    width: "max-content",
    minWidth: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
    color: tokens.colorText,
    fontSize: tokens.fontSizeXs,
  },
  tableIndexHeader: {
    position: "sticky",
    top: 0,
    left: 0,
    zIndex: 3,
    width: "42px",
    minWidth: "42px",
    padding: "7px 9px",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurfaceSunken,
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
    fontWeight: 600,
    textAlign: "right",
    "::before": {
      ...STICKY_COVER,
      top: 0,
      bottom: 0,
      left: "-2px",
      width: "2px",
    },
    "::after": {
      ...STICKY_COVER,
      top: "-2px",
      left: 0,
      right: 0,
      height: "2px",
    },
  },
  tableHeader: {
    position: "sticky",
    top: 0,
    zIndex: 2,
    minWidth: "132px",
    maxWidth: "300px",
    padding: "7px 10px",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurfaceSunken,
    textAlign: "left",
    verticalAlign: "bottom",
    "::after": {
      ...STICKY_COVER,
      top: "-2px",
      left: 0,
      right: 0,
      height: "2px",
    },
  },
  tableHeaderScrolled: {
    boxShadow: `0 6px 8px -6px ${STICKY_EDGE_SHADOW_COLOR}`,
  },
  tableIndexHeaderScrolled: {
    boxShadow: `0 6px 8px -6px ${STICKY_EDGE_SHADOW_COLOR}, 6px 0 8px -6px ${STICKY_EDGE_SHADOW_COLOR}`,
  },
  tableHeaderTitle: {
    display: "block",
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontWeight: 700,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tableHeaderType: {
    display: "block",
    marginTop: "2px",
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
    fontWeight: 500,
  },
  tableIndexCell: {
    position: "sticky",
    left: 0,
    zIndex: 1,
    width: "42px",
    minWidth: "42px",
    padding: "6px 9px",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurface,
    backgroundImage: ROW_TINT_LAYER,
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
    textAlign: "right",
    "::before": {
      ...STICKY_COVER,
      top: 0,
      bottom: 0,
      left: "-2px",
      width: "2px",
    },
  },
  tableIndexCellScrolled: {
    boxShadow: `6px 0 8px -6px ${STICKY_EDGE_SHADOW_COLOR}`,
  },
  // Marks a selected row at its number, where the tint alone is faint.
  tableIndexCellSelected: {
    boxShadow: `inset 2px 0 0 ${tokens.colorAccent}`,
  },
  tableIndexCellSelectedScrolled: {
    boxShadow: `inset 2px 0 0 ${tokens.colorAccent}, 6px 0 8px -6px ${STICKY_EDGE_SHADOW_COLOR}`,
  },
  tableCell: {
    minWidth: "132px",
    maxWidth: "300px",
    padding: "6px 10px",
    overflow: "hidden",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundImage: ROW_TINT_LAYER,
    color: tokens.colorText,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    verticalAlign: "top",
  },
  tableRow: {
    [ROW_TINT]: { default: "transparent", ":hover": tokens.colorHover },
  },
  tableRowSelected: {
    [ROW_TINT]: tokens.colorAccentSoft,
  },
  tableRowHighlighted: {
    [ROW_TINT]: tokens.colorHoverStrong,
  },
  tableRowInteractive: {
    cursor: "pointer",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    outlineOffset: "-2px",
  },
  tableCellCode: { fontFamily: MONO, fontSize: "10px" },
  tableCellNumeric: { textAlign: "right", fontVariantNumeric: "tabular-nums" },
  tableCellNull: { color: tokens.colorSubtle, fontStyle: "italic" },
  tableEmpty: {
    padding: 0,
  },
  // Pinned to the visible width, so a wide table still centers the message.
  tableEmptyMessage: {
    position: "sticky",
    left: 0,
    boxSizing: "border-box",
    width: "100cqi",
    padding: "28px 14px",
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeXs,
    textAlign: "center",
  },
  tableLimit: {
    color: tokens.colorSubtle,
    fontSize: "10px",
  },
  tablePager: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    minWidth: 0,
  },
  tablePagerMeta: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    minWidth: 0,
  },
  tablePagerActions: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
  },
  tablePagerButton: {
    minHeight: "26px",
    paddingInline: "9px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    backgroundColor: tokens.colorSurface,
    color: {
      default: tokens.colorText,
      ":disabled": tokens.colorTextDisabled,
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    fontSize: "10px",
  },
  tablePagerIconButton: {
    width: "26px",
    paddingInline: 0,
    display: "grid",
    placeItems: "center",
  },
  tablePageIndicator: {
    minWidth: "74px",
    color: tokens.colorMuted,
    fontSize: "10px",
    textAlign: "center",
    whiteSpace: "nowrap",
  },
  tablePageSize: {
    height: "26px",
    paddingInline: "6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    outlineOffset: "1px",
    backgroundColor: tokens.colorSurface,
    color: tokens.colorText,
    fontSize: "10px",
  },
  columnPickerTrigger: {
    height: "26px",
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    paddingInline: "8px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    backgroundColor: {
      default: tokens.colorSurface,
      ":hover": tokens.colorSurfaceMuted,
    },
    color: tokens.colorText,
    cursor: "pointer",
    fontSize: "10px",
  },
  columnPickerCount: {
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
  },
  columnPickerPositioner: {
    zIndex: 30,
  },
  columnPickerPopup: {
    width: "248px",
    padding: "9px",
    outline: "none",
  },
  columnPickerHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: "8px",
    paddingInline: "3px",
    paddingBottom: "7px",
  },
  columnPickerTitle: {
    color: tokens.colorTextEmphasis,
    fontSize: "10px",
    fontWeight: 750,
  },
  columnPickerHint: {
    color: tokens.colorSubtle,
    fontSize: "9px",
  },
  columnPickerList: {
    maxHeight: "236px",
    display: "grid",
    gap: "2px",
    overflowY: "auto",
    paddingBlock: "2px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  columnPickerOption: {
    display: "grid",
    gridTemplateColumns: "15px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "7px",
    padding: "6px 4px",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "10px",
  },
  columnPickerOptionTitle: {
    overflow: "hidden",
    color: tokens.colorText,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  columnPickerOptionType: {
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
  },
  columnPickerFooter: {
    display: "flex",
    justifyContent: "space-between",
    gap: "6px",
    paddingTop: "7px",
  },
  columnPickerTextButton: {
    padding: "3px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.colorAccent,
    cursor: "pointer",
    fontSize: "9px",
  },
  tableTruncatedCellButton: {
    width: "100%",
    padding: 0,
    overflow: "hidden",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.colorAccent,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "inherit",
    textAlign: "inherit",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    // A dotted underline on hover says the preview opens to the whole value.
    textDecorationLine: { default: "none", ":hover": "underline" },
    textDecorationStyle: "dotted",
    textDecorationColor: tokens.colorSubtle,
    textUnderlineOffset: "3px",
  },
  tableCellDetail: {
    display: "grid",
    gap: "6px",
    padding: "8px",
    borderRadius: "7px",
    backgroundColor: tokens.colorSurfaceSunken,
  },
  tableCellDetailHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    minWidth: 0,
    color: tokens.colorMuted,
    fontSize: "10px",
  },
  tableCellDetailTitle: {
    display: "flex",
    alignItems: "baseline",
    gap: "6px",
    minWidth: 0,
    overflow: "hidden",
    whiteSpace: "nowrap",
  },
  tableCellDetailName: {
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontWeight: 600,
    textOverflow: "ellipsis",
  },
  tableCellDetailLength: {
    flexShrink: 0,
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
  },
  tableCellDetailValue: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: "100px",
    padding: "8px",
    resize: "vertical",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: tokens.colorDivider,
      ":focus": tokens.colorBorderStrong,
    },
    borderRadius: "6px",
    outline: "none",
    backgroundColor: tokens.colorSurface,
    color: tokens.colorText,
    fontFamily: MONO,
    fontSize: "10px",
    lineHeight: 1.55,
  },
  tableDownload: {
    color: tokens.colorAccent,
    fontSize: "10px",
    textDecorationLine: "none",
  },
});
