import * as stylex from "@stylexjs/stylex";

import { tokens } from "@/lib/stylex/tokens.stylex";

/** Style keys of the table artifact renderer and its parts. */
const MONO = "ui-monospace, SFMono-Regular, Menlo, monospace";

export const s = stylex.create({
  tablePreview: {
    display: "grid",
    gap: "6px",
    minWidth: 0,
  },
  tableSummary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    color: tokens.colorMuted,
    fontSize: "10px",
  },
  tableSummaryMeta: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    whiteSpace: "nowrap",
  },
  tableSummaryStrong: {
    color: tokens.colorTextEmphasis,
    fontWeight: 700,
  },
  tableSummaryDivider: {
    color: tokens.colorDivider,
  },
  tableToolbarActions: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  tableViewport: {
    width: "100%",
    maxHeight: "420px",
    overflow: "auto",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  dataTable: {
    width: "max-content",
    minWidth: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
    color: tokens.colorText,
    fontSize: tokens.fontSizeXs,
  },
  tableIndexHeader: {
    position: "sticky",
    top: 0,
    left: 0,
    zIndex: 3,
    width: "42px",
    minWidth: "42px",
    padding: "7px 9px",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurfaceSunken,
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
    fontWeight: 600,
    textAlign: "right",
  },
  tableHeader: {
    position: "sticky",
    top: 0,
    zIndex: 2,
    minWidth: "132px",
    maxWidth: "300px",
    padding: "7px 10px",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurfaceSunken,
    textAlign: "left",
    verticalAlign: "bottom",
  },
  tableHeaderTitle: {
    display: "block",
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontWeight: 700,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tableHeaderType: {
    display: "block",
    marginTop: "2px",
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
    fontWeight: 500,
  },
  tableIndexCell: {
    position: "sticky",
    left: 0,
    zIndex: 1,
    width: "42px",
    minWidth: "42px",
    padding: "6px 9px",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurface,
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
    textAlign: "right",
  },
  tableCell: {
    minWidth: "132px",
    maxWidth: "300px",
    padding: "6px 10px",
    overflow: "hidden",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
    color: tokens.colorText,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    verticalAlign: "top",
  },
  tableCellSelected: {
    backgroundColor: tokens.colorAccentSoft,
  },
  tableCellHighlighted: {
    backgroundColor: tokens.colorHoverStrong,
  },
  tableRowInteractive: {
    cursor: "pointer",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    outlineOffset: "-2px",
  },
  tableCellCode: { fontFamily: MONO, fontSize: "10px" },
  tableCellNull: { color: tokens.colorSubtle, fontStyle: "italic" },
  tableEmpty: {
    padding: "28px 14px",
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeXs,
    textAlign: "center",
  },
  tableLimit: {
    color: tokens.colorSubtle,
    fontSize: "10px",
  },
  tablePager: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    minWidth: 0,
  },
  tablePagerMeta: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    minWidth: 0,
  },
  tablePagerActions: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
  },
  tablePagerButton: {
    minHeight: "26px",
    paddingInline: "9px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    backgroundColor: tokens.colorSurface,
    color: {
      default: tokens.colorText,
      ":disabled": tokens.colorTextDisabled,
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    fontSize: "10px",
  },
  tablePagerIconButton: {
    width: "26px",
    paddingInline: 0,
    display: "grid",
    placeItems: "center",
  },
  tablePageIndicator: {
    minWidth: "74px",
    color: tokens.colorMuted,
    fontSize: "10px",
    textAlign: "center",
    whiteSpace: "nowrap",
  },
  tablePageSize: {
    height: "26px",
    paddingInline: "6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    outlineStyle: "solid",
    outlineColor: tokens.colorAccent,
    outlineOffset: "1px",
    backgroundColor: tokens.colorSurface,
    color: tokens.colorText,
    fontSize: "10px",
  },
  columnPickerTrigger: {
    height: "26px",
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    paddingInline: "8px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    backgroundColor: {
      default: tokens.colorSurface,
      ":hover": tokens.colorSurfaceMuted,
    },
    color: tokens.colorText,
    cursor: "pointer",
    fontSize: "10px",
  },
  columnPickerCount: {
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
  },
  columnPickerPositioner: {
    zIndex: 30,
  },
  columnPickerPopup: {
    width: "248px",
    padding: "9px",
    outline: "none",
  },
  columnPickerHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: "8px",
    paddingInline: "3px",
    paddingBottom: "7px",
  },
  columnPickerTitle: {
    color: tokens.colorTextEmphasis,
    fontSize: "10px",
    fontWeight: 750,
  },
  columnPickerHint: {
    color: tokens.colorSubtle,
    fontSize: "9px",
  },
  columnPickerList: {
    maxHeight: "236px",
    display: "grid",
    gap: "2px",
    overflowY: "auto",
    paddingBlock: "2px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: tokens.colorDivider,
  },
  columnPickerOption: {
    display: "grid",
    gridTemplateColumns: "15px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "7px",
    padding: "6px 4px",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "10px",
  },
  columnPickerOptionTitle: {
    overflow: "hidden",
    color: tokens.colorText,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  columnPickerOptionType: {
    color: tokens.colorSubtle,
    fontFamily: MONO,
    fontSize: "9px",
  },
  columnPickerFooter: {
    display: "flex",
    justifyContent: "space-between",
    gap: "6px",
    paddingTop: "7px",
  },
  columnPickerTextButton: {
    padding: "3px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.colorAccent,
    cursor: "pointer",
    fontSize: "9px",
  },
  tableTruncatedCellButton: {
    width: "100%",
    padding: 0,
    overflow: "hidden",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.colorAccent,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "inherit",
    textAlign: "left",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tableCellDetail: {
    display: "grid",
    gap: "6px",
    padding: "8px",
    borderRadius: "7px",
    backgroundColor: tokens.colorSurfaceSunken,
  },
  tableCellDetailHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
    color: tokens.colorMuted,
    fontSize: "10px",
  },
  tableCellDetailValue: {
    width: "100%",
    minHeight: "100px",
    resize: "vertical",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    borderRadius: "6px",
    backgroundColor: tokens.colorSurface,
    color: tokens.colorText,
    fontFamily: MONO,
    fontSize: "10px",
  },
  tableDownload: {
    color: tokens.colorAccent,
    fontSize: "10px",
    textDecorationLine: "none",
  },
});
