import * as stylex from "@stylexjs/stylex";

import { tokens } from "@/lib/stylex/tokens.stylex";

/**
 * The chrome of the docked side panel.
 *
 * The numbers here are the Workspace rail's numbers on purpose: 8px row padding,
 * a 6px radius, 13px labels, `colorSurfaceSunken` hover, and no shadow. The rail
 * and the panel are one sidebar with two panes, and the only way they read that
 * way is by agreeing about every one of these.
 */
export const panelStyles = stylex.create({
  view: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "6px 8px 4px",
  },
  search: {
    minWidth: 0,
    flex: 1,
    height: "26px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    paddingInline: "7px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: tokens.colorBorder,
      ":focus-within": tokens.colorBorderStrong,
    },
    borderRadius: "6px",
    backgroundColor: {
      default: tokens.colorSurface,
      ":focus-within": tokens.colorBg,
    },
    color: tokens.colorSubtle,
  },
  searchInput: {
    minWidth: 0,
    flex: 1,
    borderWidth: 0,
    borderStyle: "none",
    padding: 0,
    backgroundColor: "transparent",
    color: tokens.colorText,
    fontFamily: "inherit",
    fontSize: tokens.fontSizeSm,
    outlineWidth: 0,
    ":focus": { outline: "none" },
  },
  iconButton: {
    width: "26px",
    height: "26px",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "6px",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceSunken,
      ":disabled": "transparent",
    },
    color: {
      default: tokens.colorMuted,
      ":hover": tokens.colorText,
      ":disabled": tokens.colorTextDisabled,
    },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
  },
  iconButtonActive: {
    backgroundColor: tokens.colorSurfaceRaised,
    color: tokens.colorTextEmphasis,
  },
  list: {
    minHeight: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  /** The file-drop area: it must be the positioned parent of the drop hint. */
  dropRegion: {
    position: "relative",
    minHeight: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  listViewport: { height: "100%", overscrollBehavior: "contain" },
  listContent: {
    display: "grid",
    alignContent: "start",
    gap: "1px",
    padding: "2px 6px 10px",
  },
  folderRow: {
    width: "100%",
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "5px 6px",
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "6px",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceSunken,
    },
    color: tokens.colorMuted,
    cursor: "pointer",
    textAlign: "left",
    fontSize: tokens.fontSizeSm,
    fontWeight: 560,
  },
  chevron: {
    flexShrink: 0,
    color: tokens.colorSubtle,
    transition: "transform 140ms ease",
  },
  chevronOpen: { transform: "rotate(90deg)" },
  /** Holds the chevron's column where a folder has nothing to disclose. */
  chevronSpacer: { width: "12px", flexShrink: 0 },
  folderName: {
    minWidth: 0,
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  count: {
    marginLeft: "auto",
    flexShrink: 0,
    paddingInline: "4px",
    color: tokens.colorSubtle,
    fontSize: "10px",
    fontVariantNumeric: "tabular-nums",
  },
  files: { display: "grid", gap: "1px", paddingInlineStart: "14px" },
  fileRow: {
    width: "100%",
    minWidth: 0,
    display: "grid",
    /* thumb, label, then the row action pinned to the trailing edge */
    gridTemplateColumns: "18px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "7px",
    padding: "4px 6px",
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "6px",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceSunken,
    },
    cursor: "grab",
    textAlign: "left",
    color: tokens.colorText,
    outlineWidth: 0,
    ":focus-visible": {
      outline: `2px solid ${tokens.colorAccent}`,
      outlineOffset: "-1px",
    },
  },
  fileRowSelected: {
    backgroundColor: tokens.colorSurfaceRaised,
    boxShadow: `inset 0 0 0 1px ${tokens.colorBorder}`,
  },
  fileThumb: {
    width: "18px",
    height: "18px",
    display: "grid",
    placeItems: "center",
    overflow: "hidden",
    borderRadius: "4px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    backgroundColor: tokens.colorSurfaceMuted,
    color: tokens.colorMuted,
  },
  fileThumbImage: {
    width: "100%",
    height: "100%",
    display: "block",
    objectFit: "cover",
  },
  fileCopy: { minWidth: 0, display: "grid", gap: "1px" },
  fileName: {
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 500,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fileMeta: {
    overflow: "hidden",
    color: tokens.colorSubtle,
    fontSize: "10.5px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  notice: {
    margin: 0,
    padding: "10px 8px",
    color: tokens.colorSubtle,
    fontSize: tokens.fontSizeSm,
    lineHeight: 1.45,
  },
  error: {
    margin: 0,
    padding: "8px",
    color: tokens.colorDanger,
    fontSize: tokens.fontSizeSm,
    lineHeight: 1.45,
  },
  /** A row that is clicked, never carried. */
  rowStatic: { cursor: "default" },
  /** The hover action pinned to the trailing edge of a row. */
  rowAction: {
    width: "22px",
    height: "22px",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "5px",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorHoverStrong,
    },
    color: { default: tokens.colorSubtle, ":hover": tokens.colorText },
    cursor: "pointer",
  },
  statusLink: {
    marginLeft: "8px",
    display: "inline-flex",
    alignItems: "center",
    gap: "3px",
    color: tokens.colorSubtle,
    fontWeight: 560,
    textDecoration: "none",
    ":hover": { color: tokens.colorText },
  },
  scrollbar: {
    display: "flex",
    justifyContent: "center",
    width: "8px",
    padding: "2px",
  },
  thumb: {
    width: "4px",
    borderRadius: "9999px",
    backgroundColor: tokens.colorBorderStrong,
  },
  statusBar: {
    flexShrink: 0,
    padding: "5px 10px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
    color: tokens.colorSubtle,
    fontSize: "10px",
    letterSpacing: "0.04em",
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  inspector: {
    flexShrink: 0,
    display: "grid",
    gap: "5px",
    padding: "9px 10px 11px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurfaceMuted,
  },
  inspectorTitle: {
    overflow: "hidden",
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 620,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  inspectorLabel: {
    color: tokens.colorSubtle,
    fontSize: "10px",
    fontWeight: 620,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  inspectorText: {
    color: tokens.colorMuted,
    fontSize: tokens.fontSizeSm,
    lineHeight: 1.4,
    overflowWrap: "anywhere",
  },
  inspectorMono: {
    color: tokens.colorSubtle,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "10.5px",
    overflowWrap: "anywhere",
  },
  inspectorActions: { display: "flex", flexWrap: "wrap", gap: "6px" },
  action: {
    height: "24px",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    paddingInline: "7px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    borderRadius: "6px",
    backgroundColor: {
      default: tokens.colorBg,
      ":hover": tokens.colorSurfaceSunken,
    },
    color: tokens.colorText,
    cursor: "pointer",
    fontSize: tokens.fontSizeXs,
    fontWeight: 560,
    textDecoration: "none",
  },
  dropActive: {
    backgroundColor: tokens.colorAccentSoft,
    boxShadow: `inset 0 0 0 1px ${tokens.colorAccentBorder}`,
  },
  dropHint: {
    position: "absolute",
    inset: "6px",
    display: "grid",
    placeItems: "center",
    pointerEvents: "none",
    borderRadius: "8px",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: tokens.colorAccentBorder,
    backgroundColor: tokens.colorAccentSoft,
    color: tokens.colorTextEmphasis,
    fontSize: tokens.fontSizeSm,
    fontWeight: 600,
  },
  spinner: {
    animationName: "grafy-spin",
    animationDuration: "900ms",
    animationIterationCount: "infinite",
    animationTimingFunction: "linear",
  },
  /** A row a drag is currently hovering — the target of a move. */
  rowDropTarget: {
    backgroundColor: tokens.colorAccentSoft,
    boxShadow: `inset 0 0 0 1px ${tokens.colorAccentBorder}`,
  },
  /** The trailing ⋯ on a row. Quiet until it is wanted. */
  rowActions: {
    width: "20px",
    height: "20px",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    borderWidth: 0,
    borderStyle: "none",
    borderRadius: "5px",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorHoverStrong,
    },
    color: { default: tokens.colorSubtle, ":hover": tokens.colorText },
    cursor: "pointer",
  },
  renameInput: {
    minWidth: 0,
    flex: 1,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorderStrong,
    borderRadius: "4px",
    backgroundColor: tokens.colorBg,
    color: tokens.colorTextEmphasis,
    font: "inherit",
    fontWeight: 560,
    padding: "1px 4px",
    outline: "none",
  },
  /** The app's popup layer: a row menu paints over the canvas, not under it. */
  menuPositioner: { zIndex: 80 },
  menu: {
    minWidth: "168px",
    display: "grid",
    gap: "1px",
    padding: "3px",
    borderRadius: "7px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorBorder,
    backgroundColor: tokens.colorBg,
    boxShadow: tokens.shadowNode,
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "5px 7px",
    borderRadius: "5px",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: { default: "transparent", ":hover": tokens.colorHover },
    color: { default: tokens.colorText, ":disabled": tokens.colorTextDisabled },
    cursor: "pointer",
    fontSize: tokens.fontSizeSm,
    textAlign: "left",
  },
  previewImage: {
    width: "100%",
    maxHeight: "180px",
    objectFit: "contain",
    borderRadius: "6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurfaceSunken,
  },
  previewText: {
    maxHeight: "132px",
    overflowY: "auto",
    margin: 0,
    padding: "6px 7px",
    borderRadius: "6px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.colorDivider,
    backgroundColor: tokens.colorSurfaceSunken,
    color: tokens.colorText,
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
    fontSize: "10.5px",
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
});
