[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grafy-shared"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "grafy-core",
]

[tool.uv.sources]
grafy-core = { workspace = true }

[tool.basedpyright]
extends = "../../pyproject.toml"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
